#+OPTIONS: LaTeX:dvipng

#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{amsthm}
#+LaTeX_HEADER: \newtheorem{definition}{Definition}
#+LaTeX_HEADER: \usepackage{natbib}
#+TITLE:Grand fichier centralisé des notations
[TABLE-OF-CONTENTS]

Pour éviter les conflits de notation mathématique et les conflits dans les noms de variable, tout est regroupé dans ce fichier. Si un autre fichier est en désaccord avec celui-ci, il est convenu que c'est ce fichier qui a raison (quitte à le modifier).
FIXME: Trouver un moyen de lier les notations mathématiques au code correspondant.
* Général

 - $N$ : cardinal de la base d'exemple considérée
 - $|.|$ : cardinal de l'ensemble $.$
 - $dim(.)$ : dimension de l'espace $.$
* RL
  - $S$ : Espace d'état
  - $\psi : S \rightarrow \mathbb{R}^p$ : features sur l'espace d'état
  - $\phi : S \times A \rightarrow \mathbb{R}^k$ : features sur l'espace d'état-action
  - $\omega$ : Matrice de taille $k\times 1$ permettant l'approximation d'une fonction de qualité selon la formule $Q(s,a) = \omega^T\phi(s,a)$
  - $\epsilon_{LSPI}$ : seuil servant de critère d'arrêt à LSPI, qui s'arrête après que la norme 2 entre deux valeurs consécutives de $\omega$ passe en dessous de ce seuil.
  - $T_{LSPI}$ : Nombre maximum d'itérations effectuées par LSPI avant de s'arrêter si le seuil n'a pas été atteint
  - $\lambda_{LSTDQ}$ : Coefficient de régularisation pour LSTD$Q$ utilisé dans l'expression  $\tilde \omega^\pi \leftarrow (\tilde A + \lambda Id) ^{-1}\tilde b$.
  - $\gamma_{LSTDQ}$ : Coefficient d'amortissement lors de l'estimation de $Q$ par LSTD$Q$.
  - $L_{MCip}$ : Longueur max d'une trajectoire lors d'une estimation de Monte-Carlo sur le pendule inversé
  - $M_{MCip}$ : Nombre de trajectoires lors d'une estimation de Monte-Carlo sur le pendule inversé
* IRL 
 - $l : S\times A \rightarrow \mathbb{R}$ : fonction de perte
 - $R_N$ : fonction de risque empirique
 - $Q_E : S\times A \rightarrow \mathbb{R}$ : fonction de qualité de l'expert
 - $\gamma_{\mu}$ : Coefficient d'amortissement lors du calcul de $\mu$.
 - $\lambda_{\mu}$ : Coefficient de régularisation lors du calcul de $\mu$ par LSTD$\mu$.
 - $s_0$ : Etat initial dans un MDP ou par abus de notation distribution sur les états initiaux
 - $\omega_\mu$ : Matrice de taille $k \times p$ permettant l'estimation de $\mu(s,a)$ selon la formule $\hat\mu(s,a) = \omega_\mu^T\phi(s,a)$
 - $\epsilon_{ANIRL}$ : Seuil pour l'arrêt d'ANIRL, il faut que $t$ pass en dessous de ce seuil
 - $T_{ANIRL}$ : Nombre maximum d'itérations effectuées par ANIRL si $t$ ne passe pas sous le seuil
 - $\theta$ : Vecteur de récompense tel que $R(s) = \theta^T\psi(s)$
 - $\epsilon_{SCIRL}$ : Seuil d'arrêt de SCIRL, il faut que la norme du sous-gradient passe en dessous
 - $\T_{SCIRL}$ : Nombre maximum d'itérations effectuées par SCIRL
 - $\alpha(t)$ : Pas d'apprentissage (utilisé par SCIRL)
