* Code
** LSTD
*** TODO Changer le nom omega pour LSTDmu (zeta ?)
*** TODO Factoriser le A de LSTD
    La matrice A est la même dans LSTDQ et LSTD Mu, il faudrait 
    factoriser le code.
*** TODO Factoriser LSTD on et LSTD off
    Bêtement, le code de LSTD suppose que l'on a accès à la 
    politique de l'extérieur, en  tant que fonction de S dans A.
    Ce n'est pas le cas dans le cas de l'expert, où l'on utilise
    LSTD de manière on policy. Il faudrait que on et off soient
    des wrappers vers une seule fonction qui n'utilise pas
    D mais une matrice s a s' a' ploup. 
*** TODO Factoriser les parties communes de l'ANIRL
    ANIRL avec MC et avec LSTDMu ont des parties communes.
    Ce serait une bonne idée de les factoriser dans des fonctions
    à part.
*** TODO Trouver et détruire la fuite de mémoire
*** TODO Enlever la variable g_iNb_samples
    vérifier qu'elle ne sert à rien auparavant
*** DONE Normer Theta
*** DONE Utiliser une seule banque de données
** Autres
*** TODO Transformer ErrorBars.py en un Makefile
    Il a probablement moyen de faire en sorte que la vérification des données existantes s'écrive en quelques règles simples

