#+TITLE: Gridworld
* Introduction
  The GridWorld is a classical toy problem, used and described for example in \cite{ng2000algorithms}.
* Makefiles rules
  The rules are written in the file they work with. They are recalled here, because the Makefile should only be tangled from Makefile.org. Otherwise, tangling LSPI.org, for example, would overwrite LSPI.h and LSPI.c, which is expected, but also Makefile, which is not. Therefore the other .org files only define named code snippets that are recalled and tangled here.
** Misc.
Those who do not fit in the others categories (because they fit in more than one or none of them) are aggregated here :
  #+begin_src makefile :tangle Makefile :noweb yes
<<GridWorld_make>>
<<LAFEM_Exp1_make>>
<<LSTDmu_Exp_make>>
<<TT_Exp1_make>>
<<ANIRL_Exp2_make>>
<<LSPI_Exp1_make>>
<<ANIRL_Exp3_make>>
<<SCIRL_Exp1_make>>
<<Cascading_Exp2_make>>
  #+end_src
** Code extraction
  #+begin_src makefile :tangle Makefile :noweb yes
tangle=emacs -batch --visit $1 --funcall org-babel-tangle --script ~/.emacs  >/dev/null 2>/dev/null

<<LAFEM_Exp1_code_make>>
<<LSTDmu_Exp_code_make>>
<<Generator_code_make>>
<<Simulator_code_make>>
<<TT_Exp1_code_make>>
  #+end_src
** C source to .o file
  #+begin_src make :tangle Makefile :noweb yes
  CFLAGS+= -I..
c2obj=gcc $(CFLAGS) -c $1

   #+end_src
  #+begin_src makefile :tangle Makefile :noweb yes
<<LSTDmu_Exp_c2o_make>>
<<Generator_c2o_make>>
<<Simulator_c2o_make>>
  #+end_src
** .o to .exe
  #+begin_src makefile :tangle Makefile :noweb yes
O2EXE=gcc $(LFLAGS)
<<LSTDmu_Exp_o2exe_make>>
<<Generator_o2exe_make>>
  #+end_src

** Cleaning
    #+begin_src makefile :tangle Makefile :noweb yes
<<LAFEM_Exp1_clean_make>>
<<LSTDmu_Exp_clean_make>>
<<Generator_clean_make>>
<<Simulator_clean_make>>
<<TT_Exp1_clean_make>>
<<ANIRL_Exp2_clean_make>>
<<ANIRL_Exp3_clean_make>>
<<LSPI_Exp1_clean_make>>
<<SCIRL_Exp1_clean_make>>
<<Cascading_Exp2_clean_make>>
clean: GridWorld_clean LAFEM_Exp1_clean LSTDmu_Exp_clean Generator_clean Simulator_clean TT_Exp1_clean ANIRL_Exp2_clean LSPI_Exp1_clean ANIRL_Exp3_clean SCIRL_Exp1_clean Cascading_Exp2_clean

<<LSTDmu_Exp_nuke_make>>
    #+end_src

** Inception

   #+begin_src makefile :tangle Makefile :noweb yes

Makefile:
	cat *.org > All.org; emacs -batch --visit All.org --funcall org-babel-tangle --script ~/.emacs; rm All.org
   #+end_src
