#+TITLE: The Chainwalk
* Introduction
  The chainwalk is a classical toy problem, used and described for example in \cite{lagoudakis2003least}.
  
* Makefiles rules
  The rules are written in the file they work with. They are recalled here, because the Makefile should only be tangled from Makefile.org. Otherwise, tangling LSPI.org, for example, would overwrite LSPI.h and LSPI.c, which is expected, but also Makefile, which is not. Therefore the other .org files only define named code snippets that are recalled and tangled here.
** Misc.
Those who do not fit in the others categories (because they fit in more than one or none of them) are aggregated here :
  #+begin_src makefile :tangle Makefile :noweb yes
<<lagoudakis2003least_figure10_make>>
  #+end_src
** Code extraction
  #+begin_src makefile :tangle Makefile :noweb yes
<<Generator_code_make>>
<<lagoudakis2003least_figure10_code_make>>
  #+end_src
** C source to .o file
  #+begin_src make :tangle Makefile :noweb yes
  CFLAGS+=-I..
   #+end_src
  #+begin_src makefile :tangle Makefil :noweb yes
<<Generator_c2o_make>>
<<lagoudakis2003least_figure10_c2o_make>>
  #+end_src
** .o to .exe
  #+begin_src makefile :tangle Makefile :noweb yes
<<Generator_o2exe_make>>
<<lagoudakis2003least_figure10_o2exe_make>>
  #+end_src
** Cleaning
    #+begin_src makefile :tangle Makefile :noweb yes
<<Generator_clean_make>>
<<lagoudakis2003least_figure10_clean_make>>
clean: Generator_clean lagoudakis2003least_figure10_clean
    #+end_src



** Inception

   #+begin_src makefile :tangle Makefile :noweb yes
Makefile:
	cat *.org > All.org; emacs -batch --visit All.org --funcall org-babel-tangle --script ~/.emacs; rm All.org
   #+end_src
